### ISSUE TITLE
finished the requirements

### ISSUE THREAD

**Issue by florian4300** [htl-perg-2019-20-5ahif/contact-list-exercise-florian4300#1]
@rstropek 
I didn't publish the api to azure, because I couldn't log in.
Also, somehow the validating of the Model State didn't work properly so I had to check it manually.

**Comment by rstropek** [comment]
You forgot to use *data annotations* in your model class (e.g. `[Required]`). Fix that and the extra point will be yours.

Greetings,
Rainer Stropek.

**Comment by florian4300** [comment]
@rstropek added the annotations
